#!/bin/bash

# app_apns server - Startup script for app_apns server
# chkconfig: 35 90 10
# description: app_apns server.
# processname: app_apns
# config: /etc/mx_apps/app_apns
# pidfile: /var/run/app_apns

### BEGIN INIT INFO
# Provides: app_apns
# Required-Start: $local_fs $remote_fs $network
# Required-Stop: $local_fs $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop apns
### END INIT INFO


. /etc/rc.d/init.d/functions

SERVER_NAME="Apns-Server"
SERVER_CMD="/root/.pyenv/versions/3.4.3/bin/python"
SERVER_SCP="app_apns"
SERVER_PTH="/opt/webapps/${SERVER_SCP}"
SERVER_OPT="${SERVER_SCP}.py"
SERVER_OPT_START="${SERVER_OPT} --cmd=start --conf="
SERVER_OPT_STOP="${SERVER_OPT} --cmd=stop --conf="
SERVER_TMP="/tmp/${SERVER_SCP}.tmp"
SERVER_CONFPATH="/etc/mx_apps/${SERVER_SCP}/${SERVER_SCP}_is*"

. /etc/rc.d/init.d/mxapps
